project:
  type: book

lang: zh

book:
  title: "quarto-test"
  author: "Jane Doe"
  date: "11/23/2022"
  chapters:
    - index.qmd
    - part: getting-started.qmd
      chapters:
        - intro.qmd
    - references.qmd
  appendices:
    - summary.qmd
  repo-branch: main
  search: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    include-in-header: preamble.tex
  docx:
    toc: true
    toc-depth: 3
    crossref:
      chapters: true
